apiVersion: v1
kind: Service
metadata:
  name: db
  labes:
    name: postgres-service
    app: demo-voting-app
spec:
  type: clusterIP
  port:
     -port: 5432
      targetPort: 5432
  selector:
      name: postgres-pod
      app: demo-voting-app